# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTPD-WatchLog
version:      0.04
version_from: WatchLog.pm
installdirs:  site
requires:
    Class::Accessor:               0.1
    File::Tail:                    0.5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
